### PR TITLE
RN 0.47+ android support

### PR DESCRIPTION
**Pull request by eeynard**

### CODE REVIEW

**Comment by wootwoot1234** [comment]
Thanks for the pull request.  Do you mind updating the readme with any information android users might need?

**Comment by eeynard** [comment]
Hi ! I don't see any more information I could to provide regarding this PR :)

**Comment by wootwoot1234** [comment]
Ok, cool.  Just want to make sure.  This works with older version of RN too?  If so, I'll merge.

**Comment by CookieKenku** [comment]
Please, merge this!

**Comment by wootwoot1234** [comment]
@CookieKenku I didn't test this new code.  Can you let me know if you have any issues?

**Comment by CookieKenku** [comment]
I can confirm that without this update your module won't build with the newer RN versions.
I tried to comment that @Override and it helped me to successfully build.

**Comment by CookieKenku** [comment]
Thanks for your update, by the way! But can you also make it available with NPM?

**Comment by wootwoot1234** [comment]
Done

**Pull request merged**
